function report = buildReport(caseData, params)
%BUILDREPORT  Stage 9b: compose the structured final screening report.
%
%   report = buildReport(caseData, params)
%
%   CONTRACT (docs/ARCHITECTURE.md §4.8):
%     report.data     struct (machine-readable subset of case)
%     report.summary  string (concise paragraph for rapid review)
%     report.filepath string (rendered report path; '' until renderReport)
%     report.review   struct (embedded final review/decision)
%
%   Embeds the explicit screening disclaimer (docs/ARCHITECTURE.md §10): the
%   report is decision-support, not a diagnosis, not a replacement for an
%   ophthalmologist.

    if nargin < 2 || isempty(params)
        params = experiment_config();
    end

    review = caseData.review;
    if isempty(review) || ~isfield(review, 'action')
        % Empty / uninitialized review: substitute complete defaults.
        review = struct('action', '', 'graderId', '', 'overrideGrade', NaN, ...
            'finalReferral', false, 'status', 'auto', 'notes', '', ...
            'finalGrade', caseData.grading.grade, ...
            'finalGradeLabel', gradeToLabel(caseData.grading.grade), ...
            'aiGradeImmutable', true);
    else
        % Defensive: fill fields a partial/older review struct lacks (e.g. the
        % 'reqReview' placeholder built by runPipeline). Values reflect no human
        % action: the AI grade stands as the provisional final grade.
        partialDefaults = struct( ...
            'graderId',        '', ...
            'overrideGrade',   NaN, ...
            'finalReferral',   false, ...
            'status',          'auto', ...
            'notes',           '', ...
            'finalGrade',      caseData.grading.grade, ...
            'finalGradeLabel', gradeToLabel(caseData.grading.grade), ...
            'aiGradeImmutable', true);
        fnames = fieldnames(partialDefaults);
        for i = 1:numel(fnames)
            if ~isfield(review, fnames{i})
                review.(fnames{i}) = partialDefaults.(fnames{i});
            end
        end
    end

    % Grading (and thus any grade) is only meaningful for gradeable images.
    % For ungradable images no AI grade exists: record that honestly instead of
    % inventing a grade or referral decision.
    ungradable = strcmpi(caseData.quality.class, 'ungradable') || ...
        isnan(caseData.grading.grade);
    if ungradable
        review.finalGrade       = NaN;
        review.finalGradeLabel  = 'Pending recapture';
        review.finalReferral    = false;
    end

    % --- Build machine-readable data subset ---
    if ungradable
        aiLabel = 'N/A (ungradable)';
    else
        aiLabel = gradeToLabel(caseData.grading.grade);
    end
    reportData = struct( ...
        'patientId',        caseData.meta.patientId, ...
        'eye',              caseData.meta.eye, ...
        'timestamp',        caseData.meta.timestamp, ...
        'phcId',            caseData.meta.phcId, ...
        'quality',          caseData.quality.class, ...
        'qualityScore',     caseData.quality.score, ...
        'qualityMetrics',   caseData.quality.metrics, ...
        'enhanced',         caseData.pipeline.enhanced, ...
        'grade',            caseData.grading.grade, ...
        'gradeLabel',       aiLabel, ...
        'rawProbs',         caseData.grading.rawProbs, ...
        'calibratedProbs',  caseData.calibrated.calibratedProbs, ...
        'referable',        caseData.grading.referable, ...
        'referableProb',    caseData.grading.referableProb, ...
        'confidence',       caseData.calibrated.confidence, ...
        'uncertainty',      caseData.calibrated.uncertainty, ...
        'reviewRequired',   caseData.calibrated.reviewRequired, ...
        'reviewAction',     review.action, ...
        'reviewGraderId',   review.graderId, ...
        'reviewStatus',     review.status, ...
        'reviewNotes',      review.notes, ...
        'finalGrade',       review.finalGrade, ...
        'finalGradeLabel',  review.finalGradeLabel, ...
        'aiGradeImmutable', review.aiGradeImmutable, ...
        'finalReferral',    review.finalReferral, ...
        'pipelineStarted',  caseData.pipeline.startedAt, ...
        'pipelineFinished', caseData.pipeline.finishedAt, ...
        'disclaimer',       'Screening decision-support only. Not a diagnosis and not a replacement for an ophthalmologist.');

    % pipelineStages is assigned separately: MATLAB's struct() treats a cell
    % value as dimension-expanding, which would turn reportData into a struct
    % ARRAY and break subsequent dot-field assignments.
    reportData.pipelineStages = caseData.pipeline.stages;

    % Ungradable/recapture context (honest, non-fabricated).
    if isfield(caseData.quality, 'failureReasons')
        reportData.qualityFailures = caseData.quality.failureReasons;
    else
        reportData.qualityFailures = {};
    end
    reportData.recapture = struct('reasonCode', '', 'instruction', '');
    if isfield(caseData.quality, 'recapture') && isstruct(caseData.quality.recapture) ...
            && isfield(caseData.quality.recapture, 'reasonCode')
        reportData.recapture.reasonCode = caseData.quality.recapture.reasonCode;
        if isfield(caseData.quality.recapture, 'instruction')
            reportData.recapture.instruction = caseData.quality.recapture.instruction;
        end
    end

    % --- Add retinal evidence if available ---
    if isfield(caseData, 'evidence') && isstruct(caseData.evidence)
        % Seed as a scalar struct (struct() alone yields an empty 0x0 array,
        % which cannot receive dot-field assignments).
        reportData.evidence = struct( ...
            'opticDisc', struct('detected', false, 'center', [], 'bbox', [], ...
                'confidence', 0, 'status', 'not_detected', 'method', ''), ...
            'fovea',     struct('detected', false, 'center', []), ...
            'vessels',   struct('available', false, 'density', 0), ...
            'lesions',   struct(), ...
            'advisoryConfidence', '');
        
        % Optic Disc
        if isfield(caseData.evidence, 'opticDiscDetail') && isstruct(caseData.evidence.opticDiscDetail)
            od = caseData.evidence.opticDiscDetail;
            reportData.evidence.opticDisc = struct( ...
                'detected',   ~isempty(od.center), ...
                'center',     od.center, ...
                'bbox',       od.bbox, ...
                'confidence', od.confidence, ...
                'status',     od.status, ...
                'method',     od.method);
        end

        % Fovea
        if isfield(caseData.evidence, 'fovea')
            reportData.evidence.fovea = struct( ...
                'detected', ~isempty(caseData.evidence.fovea), ...
                'center',   caseData.evidence.fovea);
        end

        % Vessel Mask
        if isfield(caseData.evidence, 'vesselMask')
            reportData.evidence.vessels = struct( ...
                'available', ~isempty(caseData.evidence.vesselMask) && nnz(caseData.evidence.vesselMask) > 0, ...
                'density',   computeVesselDensity(caseData.evidence.vesselMask));
        end

        % Lesions
        if isfield(caseData.evidence, 'lesions')
            classes = {'exudates', 'hemorrhages', 'microaneurysms', 'neoVasc'};
            lesOut = struct( ...
                'exudates',    struct('candidateCount', 0, 'hasCandidates', false, 'features', []), ...
                'hemorrhages', struct('candidateCount', 0, 'hasCandidates', false, 'features', []), ...
                'microaneurysms', struct('candidateCount', 0, 'hasCandidates', false, 'features', []), ...
                'neoVasc',     struct('candidateCount', 0, 'hasCandidates', false, 'features', []));
            for i = 1:numel(classes)
                cls = classes{i};
                if ~isfield(caseData.evidence.lesions, cls), continue; end
                les = caseData.evidence.lesions.(cls);
                lesOut.(cls) = struct( ...
                    'candidateCount',  les.count, ...
                    'hasCandidates',   les.count > 0, ...
                    'features',        les.features);
            end
            reportData.evidence.lesions = lesOut;
        end

        % Advisory confidence
        if isfield(caseData.evidence, 'confidence')
            reportData.evidence.advisoryConfidence = caseData.evidence.confidence;
        end
    end

    % --- Add explainability if available ---
    gradCamAvailable = false;
    attentionAvailable = false;
    evidenceOverlayAvailable = false;
    if isfield(caseData, 'explain') && isstruct(caseData.explain)
        % Content-based availability only (AGENTS.md #3). The attention image
        % is never advertised just because a nonempty (black/zero-map) array
        % exists: it is available ONLY when the heatmap itself is non-trivial.
        gradCamAvailable = isfield(caseData.explain, 'gradCam') ...
            && ~isempty(caseData.explain.gradCam) ...
            && any(caseData.explain.gradCam(:) > 0);
        attentionAvailable = gradCamAvailable;   % zero map -> black image, not shown
        evidenceOverlayAvailable = isfield(caseData, 'evidence') ...
            && evidenceOverlayHasContent(caseData.evidence);
        reportData.explainability = struct( ...
            'gradCamAvailable',          gradCamAvailable, ...
            'attentionImageAvailable',   attentionAvailable, ...
            'evidenceOverlayAvailable',  evidenceOverlayAvailable, ...
            'note',                      caseData.explain.note);
    end

    % --- Human-readable summary ---
    if ungradable
        failures = '';
        if isfield(reportData, 'qualityFailures') && ~isempty(reportData.qualityFailures)
            failures = strjoin(reportData.qualityFailures, ', ');
        end
        instruction = strtrim(reportData.recapture.instruction);
        if ~isempty(instruction) && instruction(end) == '.'
            instruction(end) = [];
        end
        summary = sprintf( ...
            ['Patient %s (%s eye): Image UNGRADABLE (quality score %.2f). ', ...
             'Failures: %s. Recapture requested (%s): %s. ', ...
             'No AI grade or referral decision was produced.'], ...
            caseData.meta.patientId, caseData.meta.eye, ...
            caseData.quality.score, failures, ...
            reportData.recapture.reasonCode, instruction);
    else
        summary = sprintf( ...
            ['Patient %s (%s eye): Image quality %s (score %.2f). ', ...
             'AI DR Grade %d (%s), referable=%d, referableProb=%.2f. ', ...
             'Calibrated probs [%.2f %.2f %.2f %.2f %.2f], confidence %.2f, uncertainty %.2f. ', ...
             'Review: %s (status=%s, grader=%s). Final grade: %d (%s), finalReferral: %d. ', ...
             'AI grade immutable: %d. Evidence confidence: %s.'], ...
            caseData.meta.patientId, caseData.meta.eye, ...
            caseData.quality.class, caseData.quality.score, ...
            caseData.grading.grade, gradeToLabel(caseData.grading.grade), ...
            caseData.grading.referable, caseData.grading.referableProb, ...
            caseData.calibrated.calibratedProbs, ...
            caseData.calibrated.confidence, caseData.calibrated.uncertainty, ...
            review.action, review.status, review.graderId, ...
            review.finalGrade, review.finalGradeLabel, review.finalReferral, ...
            review.aiGradeImmutable, conditionalEvidenceConfidence(caseData));
    end

    % --- Assemble report ---
    report = struct( ...
        'data',       reportData, ...
        'summary',    summary, ...
        'filepath',   '', ...          % set by renderReport
        'disclaimer', 'Screening decision-support only. Not a diagnosis and not a replacement for an ophthalmologist.', ...
        'review',     review);

    % --- Renderer images (visuals for the PDF, kept OUT of the machine-
    % readable report.data subset). Attention/evidence overlays are embedded
    % only when they contain real content (honest availability); a zero-map
    % mock yields no fake panels. The original working image is always carried.
    report.images = struct( ...
        'image',           caseData.image, ...
        'attentionImage',  [], ...
        'evidenceOverlay', [], ...
        'gradCam',         []);
    if isfield(caseData, 'explain') && isstruct(caseData.explain)
        if attentionAvailable && isfield(caseData.explain, 'attentionImage')
            report.images.attentionImage = caseData.explain.attentionImage;
        end
        if evidenceOverlayAvailable && isfield(caseData.explain, 'evidenceOverlay')
            report.images.evidenceOverlay = caseData.explain.evidenceOverlay;
        end
        if isfield(caseData.explain, 'gradCam')
            report.images.gradCam = caseData.explain.gradCam;
        end
    end

    % --- Helper functions ---
    function label = gradeToLabel(grade)
        switch grade
            case 0; label = 'No DR';
            case 1; label = 'Mild NPDR';
            case 2; label = 'Moderate NPDR';
            case 3; label = 'Severe NPDR';
            case 4; label = 'Proliferative DR';
            otherwise; label = 'Unknown';
        end
    end

    function density = computeVesselDensity(vesselMask)
        if isempty(vesselMask) || ~islogical(vesselMask)
            density = 0;
            return;
        end
        density = nnz(vesselMask) / numel(vesselMask);
    end

    function conf = conditionalEvidenceConfidence(caseData)
        if isfield(caseData, 'evidence') && isstruct(caseData.evidence) && ...
                isfield(caseData.evidence, 'confidence') && ~isempty(caseData.evidence.confidence)
            conf = caseData.evidence.confidence;
        else
            conf = 'n/a';
        end
    end

    function tf = evidenceOverlayHasContent(ev)
        % The evidence overlay draws lesion-candidate maps and a DETECTED optic
        % disc only (computeGradCAM.m). Availability is honest and mirrors what
        % is actually drawn: no candidates + no detected disc => not available.
        tf = false;
        if ~isstruct(ev); return; end
        if isfield(ev, 'lesions') && isstruct(ev.lesions)
            classes = fieldnames(ev.lesions);
            for i = 1:numel(classes)
                les = ev.lesions.(classes{i});
                if isstruct(les) && isfield(les, 'count') && les.count > 0
                    tf = true;
                    return;
                end
            end
        end
        if isfield(ev, 'opticDiscDetail') && isstruct(ev.opticDiscDetail) ...
                && isfield(ev.opticDiscDetail, 'center') ...
                && ~isempty(ev.opticDiscDetail.center)
            tf = true;
        end
    end
end