function report = buildReport(caseData, params)
%BUILDREPORT  Stage 9b: compose the structured final screening report.
%
%   report = buildReport(caseData, params)
%
%   CONTRACT (docs/ARCHITECTURE.md §4.8):
%     report.data     struct (machine-readable subset of case)
%     report.summary  string (concise paragraph for rapid review)
%     report.filepath string (rendered report path; '' until renderReport)
%     report.review   struct (embedded final review/decision)
%
%   Embeds the explicit screening disclaimer (docs/ARCHITECTURE.md §10): the
%   report is decision-support, not a diagnosis, not a replacement for an
%   ophthalmologist.

    review = caseData.review;
    if isempty(review) || ~isfield(review, 'action'); review = struct('action',''); end

    reportData = struct( ...
        'patientId',   caseData.meta.patientId, ...
        'eye',         caseData.meta.eye, ...
        'quality',     caseData.quality.class, ...
        'grade',       caseData.grading.grade, ...
        'referable',   caseData.grading.referable, ...
        'confidence',  caseData.calibrated.confidence, ...
        'uncertainty', caseData.calibrated.uncertainty, ...
        'reviewAction',  review.action, ...
        'finalReferral', review.finalReferral);

    summary = sprintf( ...
        ['Patient %s (%s): image quality %s, AI DR grade %d (referable=%d), ', ...
         'calibrated confidence %.2f, uncertainty %.2f, review %s, final referral %d.'], ...
        reportData.patientId, reportData.eye, reportData.quality, ...
        reportData.grade, reportData.referable, ...
        reportData.confidence, reportData.uncertainty, ...
        reportData.reviewAction, reportData.finalReferral);

    report = struct( ...
        'data',     reportData, ...
        'summary',  summary, ...
        'filepath', '', ...          % set by renderReport (Sprint 5)
        'disclaimer', ['Screening decision-support only. Not a diagnosis and ', ...
                       'not a replacement for an ophthalmologist.'], ...
        'review',   review);
end