function report = buildReport(caseData, params)
%BUILDREPORT  Stage 9b: compose the structured final screening report.
%
%   report = buildReport(caseData, params)
%
%   CONTRACT (docs/ARCHITECTURE.md §4.8):
%     report.data     struct (machine-readable subset of case)
%     report.summary  string (concise paragraph for rapid review)
%     report.filepath string (rendered report path; '' until renderReport)
%     report.review   struct (embedded final review/decision)
%
%   Embeds the explicit screening disclaimer (docs/ARCHITECTURE.md §10): the
%   report is decision-support, not a diagnosis, not a replacement for an
%   ophthalmologist.

    if nargin < 2 || isempty(params)
        params = experiment_config();
    end

    review = caseData.review;
    if isempty(review) || ~isfield(review, 'action'); review = struct('action',''); end

    % --- Build machine-readable data subset ---
    reportData = struct( ...
        'patientId',       caseData.meta.patientId, ...
        'eye',             caseData.meta.eye, ...
        'timestamp',       caseData.meta.timestamp, ...
        'phcId',           caseData.meta.phcId, ...
        'quality',         caseData.quality.class, ...
        'qualityScore',    caseData.quality.score, ...
        'qualityMetrics',  caseData.quality.metrics, ...
        'enhanced',        caseData.pipeline.enhanced, ...
        'grade',           caseData.grading.grade, ...
        'gradeLabel',      gradeToLabel(caseData.grading.grade), ...
        'rawProbs',        caseData.grading.rawProbs, ...
        'referable',       caseData.grading.referable, ...
        'referableProb',   caseData.grading.referableProb, ...
        'confidence',      caseData.calibrated.confidence, ...
        'uncertainty',     caseData.calibrated.uncertainty, ...
        'reviewRequired',  caseData.calibrated.reviewRequired, ...
        'reviewAction',    review.action, ...
        'reviewGraderId',  review.graderId, ...
        'reviewStatus',    review.status, ...
        'reviewNotes',     review.notes, ...
        'finalReferral',   review.finalReferral, ...
        'pipelineStages',  caseData.pipeline.stages, ...
        'pipelineStarted', caseData.pipeline.startedAt, ...
        'pipelineFinished', caseData.pipeline.finishedAt, ...
        'disclaimer',      'Screening decision-support only. Not a diagnosis and not a replacement for an ophthalmologist.');

    % --- Add retinal evidence if available ---
    if isfield(caseData, 'evidence') && isstruct(caseData.evidence)
        reportData.evidence = struct();
        
        % Optic Disc
        if isfield(caseData.evidence, 'opticDiscDetail') && isstruct(caseData.evidence.opticDiscDetail)
            od = caseData.evidence.opticDiscDetail;
            reportData.evidence.opticDisc = struct( ...
                'detected',   ~isempty(od.center), ...
                'center',     od.center, ...
                'bbox',       od.bbox, ...
                'confidence', od.confidence, ...
                'status',     od.status, ...
                'method',     od.method);
        else
            reportData.evidence.opticDisc = struct( ...
                'detected', false, 'center', [], 'bbox', [], ...
                'confidence', 0, 'status', 'not_detected', 'method', '');
        end

        % Fovea
        if isfield(caseData.evidence, 'fovea')
            reportData.evidence.fovea = struct( ...
                'detected', ~isempty(caseData.evidence.fovea), ...
                'center',   caseData.evidence.fovea);
        else
            reportData.evidence.fovea = struct('detected', false, 'center', []);
        end

        % Vessel Mask
        if isfield(caseData.evidence, 'vesselMask')
            reportData.evidence.vessels = struct( ...
                'available', ~isempty(caseData.evidence.vesselMask) && nnz(caseData.evidence.vesselMask) > 0, ...
                'density',   computeVesselDensity(caseData.evidence.vesselMask));
        else
            reportData.evidence.vessels = struct('available', false, 'density', 0);
        end

        % Lesions
        if isfield(caseData.evidence, 'lesions')
            classes = {'exudates', 'hemorrhages', 'microaneurysms', 'neoVasc'};
            reportData.evidence.lesions = struct();
            for i = 1:numel(classes)
                cls = classes{i};
                les = caseData.evidence.lesions.(cls);
                reportData.evidence.lesions.(cls) = struct( ...
                    'candidateCount',  les.count, ...
                    'hasCandidates',   les.count > 0, ...
                    'features',        les.features);
            end
        end

        % Advisory confidence
        if isfield(caseData.evidence, 'confidence')
            reportData.evidence.advisoryConfidence = caseData.evidence.confidence;
        end
    end

    % --- Add explainability if available ---
    if isfield(caseData, 'explain') && isstruct(caseData.explain)
        reportData.explainability = struct( ...
            'gradCamAvailable',    ~isempty(caseData.explain.gradCam) && any(caseData.explain.gradCam(:)), ...
            'attentionImageAvailable', ~isempty(caseData.explain.attentionImage), ...
            'evidenceOverlayAvailable', ~isempty(caseData.explain.evidenceOverlay), ...
            'note',                caseData.explain.note);
    end

    % --- Human-readable summary ---
    summary = sprintf( ...
        ['Patient %s (%s eye): Image quality %s (score %.2f). ', ...
         'AI DR Grade %d (%s, referable=%d, referableProb=%.2f). ', ...
         'Calibrated confidence %.2f, uncertainty %.2f. ', ...
         'Review: %s (status=%s), Final referral: %d. ', ...
         'Evidence confidence: %s.'], ...
        caseData.meta.patientId, caseData.meta.eye, ...
        caseData.quality.class, caseData.quality.score, ...
        caseData.grading.grade, gradeToLabel(caseData.grading.grade), ...
        caseData.grading.referable, caseData.grading.referableProb, ...
        caseData.calibrated.confidence, caseData.calibrated.uncertainty, ...
        review.action, review.status, review.finalReferral, ...
        caseData.evidence.confidence);

    % --- Assemble report ---
    report = struct( ...
        'data',       reportData, ...
        'summary',    summary, ...
        'filepath',   '', ...          % set by renderReport
        'disclaimer', 'Screening decision-support only. Not a diagnosis and not a replacement for an ophthalmologist.', ...
        'review',     review);

    % --- Helper functions ---
    function label = gradeToLabel(grade)
        switch grade
            case 0; label = 'No DR';
            case 1; label = 'Mild NPDR';
            case 2; label = 'Moderate NPDR';
            case 3; label = 'Severe NPDR';
            case 4; label = 'Proliferative DR';
            otherwise; label = 'Unknown';
        end
    end

    function density = computeVesselDensity(vesselMask)
        if isempty(vesselMask) || ~islogical(vesselMask)
            density = 0;
            return;
        end
        density = nnz(vesselMask) / numel(vesselMask);
    end
end