"""Report service — adapter layer between the backend and existing MATLAB reporting.

The existing reporting/ module (buildReport.m, renderReport.m) is MATLAB code
and cannot be called directly from Python.  This service:

1. Checks if a report artifact (JSON) was already stored by the pipeline.
2. If not, ``generate_report`` builds one honestly from the stored case data
   (quality, AI prediction, explainability, human review, final decision) and
   persists it so it can be retrieved later.
3. Provides a clean interface for future direct MATLAB report generation.

NEVER fabricates clinical output — ``generate_report`` assembles only values
that were already written to the database by the screening and review paths.
"""
from __future__ import annotations

from typing import Any

from ..storage import database_store
from ..utils.errors import ErrorCode, RetinaSenseError


def get_report(case_id: str) -> dict[str, Any]:
    """Return the stored report for *case_id*.

    If the MATLAB pipeline already produced and stored a report, it is
    returned.  Otherwise REPORT_UNAVAILABLE is raised — the backend does
    not fabricate clinical reports.
    """
    if not database_store.case_exists(case_id):
        raise RetinaSenseError(
            ErrorCode.CASE_NOT_FOUND,
            f"Case '{case_id}' not found.",
            stage="storage",
        )

    stored = database_store.load_report(case_id)
    if stored is None:
        raise RetinaSenseError(
            ErrorCode.REPORT_UNAVAILABLE,
            "No report available for this case yet. "
            "Reports are generated by the MATLAB pipeline after screening.",
            stage="reporting",
        )

    return {
        "caseId": case_id,
        "report": stored,
        "summary": stored.get("summary"),
        "disclaimer": stored.get("disclaimer"),
    }


def _build_summary(case_id: str, meta: dict, screening: dict, review_data: dict | None) -> str:
    """Compose an honest, concise summary string from real stored values."""
    parts: list[str] = [f"Case {case_id}"]

    eye = meta.get("eye")
    if eye:
        parts[0] += f" (eye {eye})"

    quality = screening.get("quality", {})
    q_class = quality.get("class")
    q_score = quality.get("score")
    if q_class:
        q_str = q_class.capitalize()
        if q_score is not None:
            q_str += f" (score {q_score:.0%})"
        parts.append(f"Quality: {q_str}.")

    ai = screening.get("aiPrediction")
    if ai and ai.get("grade") is not None:
        g = ai["grade"]
        label = ai.get("gradeLabel", f"Grade {g}")
        ref = ai.get("referable")
        parts.append(f"AI grade: {g} ({label}), referable: {'yes' if ref else 'no'}.")
    elif screening.get("status") == "recapture_required":
        parts.append("Image ungradable — no AI grade assigned.")

    if review_data:
        action = review_data.get("review", {}).get("action")
        reviewer = review_data.get("review", {}).get("reviewerId")
        if action:
            r_str = f"Human review: {action}"
            if reviewer:
                r_str += f" (reviewer {reviewer})"
            parts.append(r_str + ".")
        fd = review_data.get("finalDecision")
        if fd and fd.get("grade") is not None:
            fg = fd["grade"]
            fl = fd.get("gradeLabel", f"Grade {fg}")
            fr = fd.get("referral")
            parts.append(f"Final decision: grade {fg} ({fl}), referable: {'yes' if fr else 'no'}.")
    else:
        parts.append("No human review recorded yet.")

    disclaimer = (
        "Screening decision-support only. "
        "Not a diagnosis and not a replacement for an ophthalmologist."
    )
    parts.append(disclaimer)
    return " ".join(parts)


def generate_report(case_id: str) -> dict[str, Any]:
    """Build a structured report from the real stored case data.

    This is idempotent — calling it again for the same case overwrites the
    previous report entry with the current state of the case.  The assembled
    payload contains only values already persisted by the screening or review
    paths; nothing clinical is invented.
    """
    if not database_store.case_exists(case_id):
        raise RetinaSenseError(
            ErrorCode.CASE_NOT_FOUND,
            f"Case '{case_id}' not found.",
            stage="storage",
        )

    screening = database_store.load_screening(case_id)
    if screening is None:
        raise RetinaSenseError(
            ErrorCode.REPORT_UNAVAILABLE,
            "No screening has been run for this case yet. "
            "Reports are generated from completed screening results.",
            stage="reporting",
        )

    meta = database_store.load_metadata(case_id) or {}
    review_data = database_store.load_review(case_id)

    disclaimer = (
        "Screening decision-support only. "
        "Not a diagnosis and not a replacement for an ophthalmologist."
    )
    quality = screening.get("quality", {})
    ai_pred = screening.get("aiPrediction")
    explain = screening.get("explainability")
    fd = review_data.get("finalDecision") if review_data else None
    hr = review_data.get("review") if review_data else None

    report_payload: dict[str, Any] = {
        "caseId": case_id,
        "status": screening.get("status", "created"),
        "screeningAt": screening.get("createdAt"),
        "patientId": meta.get("patientId", ""),
        "eye": meta.get("eye", ""),
        "phcId": meta.get("phcId", ""),
        "quality": quality,
        "aiPrediction": ai_pred,
        "explainability": explain,
        "humanReview": hr,
        "finalDecision": fd,
        "disclaimer": disclaimer,
    }

    summary = _build_summary(case_id, meta, screening, review_data)
    report_payload["summary"] = summary

    database_store.save_report(case_id, report_payload)

    return {
        "caseId": case_id,
        "report": report_payload,
        "summary": summary,
        "disclaimer": disclaimer,
    }
