"""Report service — adapter layer between the backend and existing MATLAB reporting.

The existing reporting/ module (buildReport.m, renderReport.m) is MATLAB code
and cannot be called directly from Python.  This service:

1. Checks if a report artifact (JSON) was already stored by the pipeline.
2. If not, returns REPORT_UNAVAILABLE so the caller knows no report exists yet.
3. Provides a clean interface for future direct MATLAB report generation.

NEVER fabricates report content.
"""
from __future__ import annotations

from typing import Any

from ..storage import local_store
from ..utils.errors import ErrorCode, RetinaSenseError


def get_report(case_id: str) -> dict[str, Any]:
    """Return the report for *case_id*.

    If the MATLAB pipeline already produced and stored a report, it is
    returned.  Otherwise REPORT_UNAVAILABLE is raised — the backend does
    not fabricate clinical reports.
    """
    if not local_store.case_exists(case_id):
        raise RetinaSenseError(
            ErrorCode.CASE_NOT_FOUND,
            f"Case '{case_id}' not found.",
            stage="storage",
        )

    stored = local_store.load_report(case_id)
    if stored is None:
        raise RetinaSenseError(
            ErrorCode.REPORT_UNAVAILABLE,
            "No report available for this case yet. "
            "Reports are generated by the MATLAB pipeline after screening.",
            stage="reporting",
        )

    return {
        "caseId": case_id,
        "report": stored,
        "summary": stored.get("summary"),
        "disclaimer": (
            "Screening decision-support only. "
            "Not a diagnosis and not a replacement for an ophthalmologist."
        ),
    }
