function p = preprocess_config()
%PREPROCESS_CONFIG  Image preprocessing configuration (config/preprocess_config.m).
%
%   p = preprocess_config()
%
%   Used by preprocessing/ingestImage.m (downscale) and preprocessing/
%   enhanceImage.m (CLAHE + illumination normalization + denoising).
%
%   References: docs/ARCHITECTURE.md §2 Stages 0, 3, 4.

    p = struct();

    % ---- Ingestion / downscale (Stage 0) ----
    p.maxWorkingSize = 1024;   % max edge length in px, aspect preserved
    p.inputFormats   = {'.jpg', '.jpeg', '.png'};

    % ---- Adaptive enhancement (Stage 3) ----
    p.enhance = struct( ...
        'clahe',           struct( ...
                               'numTiles',    [8 8], ...
                               'clipLimit',   0.02, ...
                               'distribution','rayleigh'), ...
        'illumNorm',       struct( ...
                               'gamma',       0.85, ...   % illumination correction gamma
                               'scaleImage',  1.0), ...
        'denoise',         struct( ...
                               'method',      'gaussian', ... % 'gaussian' | 'median' | 'guided'
                               'sigma',       1.0, ...
                               'medSize',     [3 3], ...
                               'guidedR',     4, ...
                               'guidedEps',   0.1), ...
        'applyIllum',      true, ...   % enable illumination normalization
        'applyDenoise',    true);      % enable denoising

    % ---- Classifier input size (Stage 6); set to backbone standard later ----
    p.classifierInput = [224 224 3];
end